Question:

class MyException1 extends Exception {
	public MyException1() {
	}
}

class MyException2 extends Exception {
	public MyException2() {
	}
}

class ExceptionTest {
	public static void main(String[] args) throws Exception {
		try {
			m2();
		} finally {
			m3();
		} catch (MyException2 e) {
		}
		
	}

	public static void m2() throws MyException1 {
		throw new MyException1();
	}

	public static void m3() throws MyException2 {
		throw new MyException2();
	}
}

Options:
A. It will compile but will throw MyException1 when run.
B. It will compile but will throw MyException2 when run.
C. It will compile and run without throwing any exceptions.
D. It will not compile.

Answer: D

Explaination : catch block will come after try block